name: securedauth
main: com.dionplugins.securedauth.Plugin
version: 1.0.0
api-version: 1.16
commands:
  register:
    description: Create a new account
    usage: /register <password> <confirm>
    aliases: ["r", "reg", "regist"]
  login:
    description: Login to a registered account
    usage: /login <password>
    aliases: ["l", "lg", "ln"]
  unregister:
    description: Unregisters an account to the server
    usage: /unregister <current password>
    aliases: ["unr", "unreg", "unregist"]
  changepass:
    description: Changes the current password
    usage: /unregister <old password> <new password>
    aliases: ["cp", "changepassword", "chpass", "chp"]